### ISSUE TITLE
Container dependency in `RequestBuilder::sendAsAdmin`

### ISSUE THREAD

**Issue by nebkam** [nebkam/fluent-test#2]
Since `RequestBuilder::sendAsAdmin` determines admin credentials from the DIC at runtime, it requires that *container* is available.
This prevents it from being used i.e. in `tearDownAfterClass` where, I think, the kernel is already terminated and there is no reference to the container.

This is the error I'm getting, because `getContainer()` returns NULL:
```
PHP Fatal error:  Uncaught Error: Call to a member function getParameter() on null in /var/www/4z/api_v3/vendor/nebkam/fluent-test/src/RequestBuilder.php:157
Stack trace:
#0 /var/www/4z/api_v3/tests/AppBundle/Controller/BaseControllerTest.php(385): Nebkam\FluentTest\RequestBuilder->sendAsAdmin()
#1 /var/www/4z/api_v3/tests/AppBundle/Controller/External/DemandAdControllerTest.php(271): AppBundle\Controller\BaseControllerTest::deleteUserById(86147)
#2 /var/www/4z/api_v3/vendor/bin/.phpunit/phpunit-5.7/src/Framework/TestSuite.php(738): AppBundle\Controller\External\DemandAdControllerTest::tearDownAfterClass()
#3 /var/www/4z/api_v3/vendor/bin/.phpunit/phpunit-5.7/src/Framework/TestSuite.php(733): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#4 /var/www/4z/api_v3/vendor/bin/.phpunit/phpunit-5.7/src/TextUI/TestRunner.php(517): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#5 /var/www/4z/api_v3/vendor/bin/.phpunit/phpunit-5.7/src/TextUI/Command.php(186): PHPUnit_TextUI_TestRunner->do in /var/www/4z/api_v3/vendor/nebkam/fluent-test/src/RequestBuilder.php on line 157
```
Maybe read and store admin credentials on `RequestBuilder::create`` ?

**Comment by nebkam** [comment]
Deprecated `RequestBuilder::sendAsAdmin` in https://github.com/nebkam/fluent-test/commit/85cd8303b0cae648fb7dcedf91251562497ee961
Credentials can be stored with `setDefaultUsername` and `setDefaultPassword` at any time, while the DIC is available
